{{- if .Values.enabled }}
{{- if eq .Values.vosk.deploymentType "DaemonSet" }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "vosk") }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "vosk")) | nindent 4 }}
spec:
  revisionHistoryLimit: {{ .Values.vosk.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "vosk") | nindent 6 }}
  {{- with .Values.vosk.updateStrategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "helper.component.podTemplate" (dict "root" . "name" "vosk" "component" .Values.vosk) | nindent 4 }}
{{- end }}
{{- end }}
