{{- if .Values.enabled }}
{{- if eq .Values.vosk.deploymentType "StatefulSet" }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "helper.componentFullname" (dict "root" . "componentName" "vosk") }}
  labels: {{- include "helper.labels" (dict "root" . "componentName" "vosk") | nindent 4 }}
spec:
  {{- if not .Values.vosk.autoscaling.enabled }}
  replicas: {{ .Values.vosk.replicaCount }}
  {{- end }}
  revisionHistoryLimit: {{ .Values.vosk.revisionHistoryLimit | default 10 }}
  selector:
    matchLabels: {{- include "helper.selectorLabels" (dict "root" . "componentName" "vosk") | nindent 6 }}
  serviceName: {{ include "helper.componentFullname" (dict "root" . "componentName" "vosk") }}
  {{- with .Values.vosk.updateStrategy }}
  updateStrategy: {{- toYaml . | nindent 4 }}
  {{- end }}
  template:
    {{- include "helper.component.podTemplate" (dict "root" . "name" "vosk" "component" .Values.vosk) | nindent 4 }}
  {{- if or .Values.vosk.volumeClaims .Values.vosk.extraVolumeClaims }}
  volumeClaimTemplates: {{- toYaml (concat (default (list) .Values.vosk.volumeClaims) (default (list) .Values.vosk.extraVolumeClaims)) | nindent 2 }}
  {{- end }}
{{- end }}
{{- end }}
