{{- if .Values.enabled }}
{{- if and .Values.tts.serviceAccount.enabled .Values.tts.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.tts.serviceAccount.name | default (include "helper.componentFullname" (dict "root" . "componentName" "tts")) }}
  labels: {{- (include "helper.labels" (dict "root" . "componentName" "tts")) | nindent 4 }}
  {{- if .Values.tts.serviceAccount.annotations }}
  annotations:
    {{- tpl (toYaml .Values.tts.serviceAccount.annotations) . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.tts.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
